### ISSUE TITLE
[Anon] Bug report: Goblin and Orc List.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/oathmark#14]
**File:** Goblin and Orc List.catz

**BattleScribe version:** 2.03.15

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Orc Spellcaster, only choose from General & Human Spells.
Should allow selection from General & Orc and Goblin spell lists

**Comment by Miniatorium** [comment]
Have fixed this issue in the upcoming release!
